bilety/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { registrations: 'user/registrations' }
  # => { registrations: 'registrations',  sessions: 'sessions'}
  resources :tickets
  resources :events, :only => [:index, :new, :create, :show]
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bilety/app/models/ticket.rb
class Ticket < ApplicationRecord
	validates :price, :presence => true
	validates :event_id, :presence => true
	belongs_to :event
	belongs_to :user
	validate :there_are_seats_available, on: :create
	validate :ticket_limit_in_range, on: :create
	validate :event_price_range_is_correct
	validate :event_taking_place_in_the_month
	validate :juvenile_cant_buy_adult_event_ticket, on: :create

	def juvenile_cant_buy_adult_event_ticket
		if event.adultsOnly && user.date_of_birth+18.year > event.event_date
			errors.add('Adult only event', ': you cannot buy ticket for this event')
		end
	end

	def event_taking_place_in_the_month
		if Date.today-1.month > event.event_date
			errors.add('Event date', 'is too late to buy a ticket for it yet')
		end
		if Date.today > event.event_date
			errors.add('Event date', 'is in the past - cannot buy a ticket for the past event')
		end
	end

	def event_price_range_is_correct
		if price < event.price_low
			errors.add('Price', 'is lower than the lowest acceptable price for the ticket')
		end
		if Date.today != event.event_date && price > event.price_high
			errors.add('Price', 'is higher than the highest acceptable price for the ticket')
		end
		if Date.today == event.event_date && price != (event.price_high + event.price_high*0.2).round(2) 
			errors.add('Price', 'on ticket bought in the event day is '+ (event.price_high + event.price_high*0.2).round(2).to_s)
		end
	end

	def there_are_seats_available
		if event.maxSeats != nil && event.maxSeats != 0 && event.maxSeats <= event.tickets.size
			errors.add('Ticket limit', 'for this event has been expended')
		end
	end

	def ticket_limit_in_range
		if event.singleBuyerLimit != nil && event.singleBuyerLimit != 0 && event.singleBuyerLimit <= user.tickets.where(event_id: event_id).count
			errors.add('Ticket limit', 'for this buyer has been expended')
		end
	end
end

bilety/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = current_user.tickets().new()
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets().new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:seat_id_seq, :price, :event_id, :user_id)
    end
    def correct_user
      @ticket = current_user.tickets.find_by(id: params[:id])
      redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
    end
end

bilety/app/helpers/tickets_helper.rb
module TicketsHelper
end

bilety/app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :ticket_event_id %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bilety/app/views/tickets/_showevents.html.erb
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Artist</th>
      <th>Description</th>
      <th>Price (low)</th>
      <th>Price (high)</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.artist %></td>
        <td><%= event.description %></td>
        <td><%= event.price_low %></td>
        <td><%= event.price_high %></td>
        <td><%= event.event_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

bilety/app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

bilety/app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.user.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.price %></td>
        <td><%= link_to 'Show', ticket %></td>
        <% if ticket.user == current_user %>
          <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
          <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

bilety/app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= render 'showevents', events: Event.all %>

<%= link_to 'Back', tickets_path %>

bilety/app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner name:</strong>
  <%= @ticket.user.name %>
</p>

<p>
  <strong>Seat id seq:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<% if @ticket.user == current_user %>
<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<% end %>
<%= link_to 'Back', tickets_path %>