bilety/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { registrations: 'user/registrations' }
  # => { registrations: 'registrations',  sessions: 'sessions'}
  resources :tickets
  resources :events, :only => [:index, :new, :create, :show]
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bilety/app/models/event.rb
class Event < ApplicationRecord
	validates :artist, :presence => true
	validates :price_low, :presence => true
	validates :price_high, :presence => true
	validates :event_date, :presence => true
	has_many :tickets
	validate :event_price_range_is_correct
	validate :event_date_not_from_past
	def event_price_range_is_correct
		if price_low > price_high
			errors.add('Price lower range', 'cannot be higher than price higher range')
		end
		if price_high < price_low
			errors.add('Price higher range', 'cannot be lower than price lower range')
		end
	end

	def event_date_not_from_past
		if event_date < Date.today
		errors.add('Data wydarzenia', 'nie może być z przeszłości')
		end
	end
end

bilety/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]
  before_action :check_logged_in, only: [:new, :create]
  def index
    @events = Event.where("event_date >= ?", Date.today)

    @pastevents = Event.where("event_date < ?", Date.today)
  end

  def new
  	@event = Event.new
  end

  def create

  end
  def create
    #may be a duplicate, but i am too afraid of removing it
	event_parameters = params.require(:event).permit(:artist, :description,
	:price_low, :price_high, :event_date, :maxSeats, :adultsOnly, :singleBuyerLimit)
	@event = Event.new(event_parameters)
	if @event.save
	flash[:komunikat] = 'Event został poprawnie stworzony.'
	redirect_to "/events/#{@event.id}"
	else
	render 'new'
	end
end

  private
   # Use callbacks to share common setup or constraints between actions.
   def check_logged_in
		authenticate_or_request_with_http_basic("Ads") do |username, password|
		username == "admin" && password == "admin"
	end
end
    def set_event
       @event = Event.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date, :maxSeats, :adultsOnly, :singleBuyerLimit)
    end
end

bilety/app/helpers/events_helper.rb
module EventsHelper
end

bilety/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :event_artist %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description %>
  </div>

  <div class="field">
    <%= form.label :price_low %>
    <%= form.number_field :price_low, id: :event_price_low, step: 0.01, min: 0 %>
  </div>

  <div class="field">
    <%= form.label :price_high %>
    <%= form.number_field :price_high, id: :event_price_high, step: 0.01, min: 0 %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_field :event_date, id: :event_event_date%>
  </div>

  <div class="field">
    <%= form.label :maxSeats %>
    <%= form.number_field :maxSeats, id: :event_maxSeats, min: 0, step: 1%>
  </div>

  <div class="field">
    <%= form.label :adultsOnly %>
    <%= form.check_box :adultsOnly, id: :event_adultsOnly%>
  </div>

  <div class="field">
    <%= form.label :singleBuyerLimit %>
    <%= form.number_field :singleBuyerLimit, id: :event_singleBuyerLimit, min: 0, step: 1%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bilety/app/views/events/_new_ticket.html.erb
<h1>New Ticket</h1>

<%= render 'ticketform', ticket: ticket %>

bilety/app/views/events/_ticketform.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <%= form.hidden_field :event_id, id: :event_id %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bilety/app/views/events/_tickets_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>User id</th>
      <th>Seat id seq</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.user.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

bilety/app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

bilety/app/views/events/index.html.erb
<h1> Wszystkie wydarzenia</h1>
<ul>
<% for event in @events %>
<li><%= link_to event.artist, event %></li>
<% end %>
</ul>

<h1> Poprzednie wydarzenia</h1>
<ul>
<% for event in @pastevents %>
<li><%= link_to event.artist, event %></li>
<% end %>
</ul>
<%= link_to 'Nowe ogłoszenie', new_event_path %>

bilety/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

bilety/app/views/events/show.html.erb
<p id="komunikat"><%= flash[:komunikat] %></p>
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @event.id %>
</p>

<p>
  <strong>Wydarzenie:</strong>
  <%= @event.artist %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Cena (dolny próg):</strong>
  <%= @event.price_low %>
</p>

<p>
  <strong>Cena (górny próg):</strong>
  <%= @event.price_high %>
</p>

<p>
  <strong>Data wydarzenia:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Limit biletów:</strong>
  <%= @event.maxSeats %>
</p>

<p>
  <strong>Wyłącznie dla dorosłych:</strong>
  <%= @event.adultsOnly %>
</p>

<p>
  <strong>Ilość biletów możliwa do zakupu przez jedną osobę:</strong>
  <%= @event.singleBuyerLimit %>
</p>

<%= if @event.event_date >= Date.today
   render "new_ticket", ticket: Ticket.new(:event_id=>@event.id)
end %>

<%= render "tickets_list", tickets: @event.tickets %>

<%= link_to 'Back', events_path %>